name: BGG Data Mine
run-name: Update BGG data mining datasets
on:
  schedule:
    - cron: '0 0 1 * *' # every month
  workflow_dispatch:
jobs:
  BGG-Data-Mine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: abatilo/actions-poetry@v2
      - run: npm install
      - run: npm run bgg-data-mine
      - uses: peter-evans/create-pull-request@v4
